### ISSUE TITLE
Anyone considering i18n?

### ISSUE THREAD

**Issue by jeremy0519** [saurabhdaware/text-to-handwriting#16] opened 2020-04-26 02:15 UTC

**Comment by saurabhdaware** [comment] 2020-04-26 03:13
I wouldd loveeee to do thatt✨


Keeping this open for contributions!

Thank you for bringing this up🌻

**Comment by saurabhdaware** [comment] 2020-05-03 09:56
I did this in some amount in 07e47933efd433602bd1404f5d9ccd2011a425ba 

Now if the user is from china, the default language changes to the one that supports mandarin and the lorem ipsum changes as well.

![A screenshot of text-to-handwriting that shows the default language is turned into the Chinese one and new text is added](https://user-images.githubusercontent.com/30949385/80911111-ead64600-8d51-11ea-8147-f924de32708c.png)

I believe the form inputs must be translatable by the browser's default translators. Do let me know if there are any other issues that people who have different native languages face.

**Comment by jeremy0519** [comment] 2020-05-06 07:20
It seems doesn’t work well

**Comment by saurabhdaware** [comment] 2020-05-06 08:29
May I know which part is not working? It's kind of hard for me to debug since I have to depend on Google Translator

**Comment by jeremy0519** [comment] 2020-05-06 12:56
I am now in China and the language does not switch to Chinese.

**Comment by saurabhdaware** [comment] 2020-05-06 13:21
```js
fetch('http://ip-api.com/json')
  .then(res => res.json())
  .then(response => {
      console.log(response.country);
  }
```

Can you try running this in your browser console? This is what I use in code to check the country and if it returns 'China' then I switch to chinese


EDIT:

Oh I figured it out. It's because the API is using `http` I will have to find an API that uses `https`

**Comment by cesaryuan** [comment] 2020-05-06 13:26
> ```js
> fetch('http://ip-api.com/json')
>   .then(res => res.json())
>   .then(response => {
>       console.log(response.country);
>   }
> ```
> 
> Can you try running this in your browser console? This is what I use in code to check the country and if it returns 'China' then I switch to chinese

![image](https://user-images.githubusercontent.com/35998162/81182296-3140d480-8fe0-11ea-889d-f80167882e15.png)
Maybe you can use the `navigator.language`

**Comment by saurabhdaware** [comment] 2020-05-06 13:32
Should be fixed now. Can you check if it is working? I removed the iplookup API and now checking country with `navigator.language`. 8bbca45453307072982228e4c581c3a9ec1f3b0d

**Comment by saurabhdaware** [comment] 2020-05-06 13:33
Yes I moved it to @cesaryuan . Thank you!

**Comment by cesaryuan** [comment] 2020-05-06 13:34
> ```js
> fetch('http://ip-api.com/json')
>   .then(res => res.json())
>   .then(response => {
>       console.log(response.country);
>   }
> ```
> 
> Can you try running this in your browser console? This is what I use in code to check the country and if it returns 'China' then I switch to chinese

And even the ip-api works, it can have unexpected results. Because we usually use the vpn which could make our ip address incorrect.

**Comment by cesaryuan** [comment] 2020-05-06 13:49
> Should be fixed now. Can you check if it is working? I removed the iplookup API and now checking country with `navigator.language`. [8bbca45](https://github.com/saurabhdaware/text-to-handwriting/commit/8bbca45453307072982228e4c581c3a9ec1f3b0d)

It works for me!

**Comment by saurabhdaware** [comment] 2020-05-07 04:41
Perfect! Also, I guess the issue is resolved then if there's anything more to add for i18n do let me know and we can reopen this. 

Thank you @jeremy0519 :D

**Closed as completed by saurabhdaware** 2020-05-07 04:41 UTC
Labels: help wanted
