### ISSUE TITLE
the image generated is is not clear.

### ISSUE THREAD

**Issue by rishabharidas** [saurabhdaware/text-to-handwriting#25] opened 2020-05-25 13:11 UTC
the image generated is is not clear when using custom fonts(new handwritten fonts). even though the preview is looking great.

![image](https://user-images.githubusercontent.com/22971553/82815736-617ce400-9eb7-11ea-8986-805e6002adf4.png)

**Comment by saurabhdaware** [comment] 2020-05-25 13:21
Is it only happening in pdf? can you check the output of image?

**Comment by rishabharidas** [comment] 2020-05-25 13:24
no the image generated in the webpage  is also like this

![image](https://user-images.githubusercontent.com/22971553/82816657-2da2be00-9eb9-11ea-8f60-8ae8a83525cd.png)

**Comment by rishabharidas** [comment] 2020-05-25 13:26
![image](https://user-images.githubusercontent.com/22971553/82816750-5460f480-9eb9-11ea-88de-a6eef2f12515.png)

**Comment by saurabhdaware** [comment] 2020-05-25 13:30
I tried it with my handwriting file and it seems to work well for me
![Screenshot of image with my handwriting that shows the image is clear](https://user-images.githubusercontent.com/30949385/82816999-ccc7b580-9eb9-11ea-823f-11030dbd9128.png)

Can you mention the device, browser, and operating system you tested it on?

**Comment by rishabharidas** [comment] 2020-05-25 13:32
using latest edge.windows
i have mailed the font i used

**Comment by saurabhdaware** [comment] 2020-05-25 13:56
![image](https://user-images.githubusercontent.com/30949385/82818381-42cd1c00-9ebc-11ea-91e9-521ac33a49fb.png)

This is how it looks in my device, it looks similar to the input (I tested it in chrome and firefox in ubuntu). 

The font is a little unclear but still, the output in windows is not supposed to look blurred. I'll try to test it in windows by tomorrow and see if the problem is in windows.

About the font-spacing, there is a [font spacing issue in html2canvas](https://github.com/niklasvh/html2canvas/issues/2190), the library that we use internally so for the workaround there is word-spacing and letter-spacing customization option in the tool.

**Comment by rishabharidas** [comment] 2020-05-25 14:14
the text looks more clear in the preview side and less clear in the image side. basically teachers need it a bit more clearer. thats why i complained. hope u understand

**Comment by saurabhdaware** [comment] 2020-05-25 14:17
yes yes it's a fair issue, I'll check it out in windows and see if we can do something

**Comment by saurabhdaware** [comment] 2020-05-26 07:36
![screenshot of image from windows that shows the image is clear](https://user-images.githubusercontent.com/30949385/82872961-68f0cb80-9f51-11ea-8ef9-30e46a02aefa.png)

This is from windows chrome, It looks fine in the image. I will check in edge as well

**Comment by rishabharidas** [comment] 2020-05-26 08:52
try checking the pdf try to zoom it. some fonts are ok

**Comment by rishabharidas** [comment] 2020-05-26 08:55
this is what im getting with my font. even in the pdf
![assignment](https://user-images.githubusercontent.com/22971553/82880924-a9a21200-9f5c-11ea-8533-4892f21504f2.png)

**Comment by rishabharidas** [comment] 2020-05-26 09:12
![image](https://user-images.githubusercontent.com/22971553/82882033-2386cb00-9f5e-11ea-9104-3a74a6a4a71f.png)
i tried with brave browser  . and didnt got it so different
![assignment (1)](https://user-images.githubusercontent.com/22971553/82882120-487b3e00-9f5e-11ea-8165-37e0b9aa0071.png)
 should i make a font with bold writtings t make it clear. coz last time i used normal pen to make font.and maybe the ltters was too small

**Comment by rishabharidas** [comment] 2020-05-26 09:13
![assignment (1)](https://user-images.githubusercontent.com/22971553/82882724-19190100-9f5f-11ea-9fbf-b51b50b40721.jpeg)
was bettr with another custom font . maybe u should make the page a bit more clearer
coz when zooimg pdf
![image](https://user-images.githubusercontent.com/22971553/82883523-2da9c900-9f60-11ea-85be-768554fe8e83.png)

**Comment by saurabhdaware** [comment] 2020-05-26 19:07
Oh yes it looks off in PDFs even in Ubuntu. 

How about acting as if it is a feature :c? I mean if you turn images to a PDF with some online software, they get blurred as well so isn't that making it look more legit? 

But yes in some cases, like in case of your font, that blurriness will make the text unreadable. 

I'll think and I guess I'll have to check the [jsPDF docs](https://github.com/MrRio/jsPDF) (the library we use to convert images to PDF)

Let me know your thoughts as well

**Comment by rishabharidas** [comment] 2020-05-30 16:10
more like bugs = features 😁 yeah !  Maybe u should give a guide to the font creation which will better match with your project

**Comment by saurabhdaware** [comment] 2020-06-26 06:36
I'm trying to solve this along with the new design. I am not sure if it will work out but let's see.

**Comment by Jobin-S** [comment] 2020-07-30 08:27
can you please add me as the contributor on the site. I contributed here #71

**Comment by saurabhdaware** [comment] 2020-07-30 08:35
Hi @Jobin-S  It is supposed to show up automatically after some time. It fetches contributors from GitHub Contributors.

**Comment by saurabhdaware** [comment] 2020-07-30 08:36
Oh and I resolved this issue sometime back. Now I don't remember which commit 🤦‍♂️ but it is apparently fixed now

**Closed as completed by saurabhdaware** 2020-07-30 08:36 UTC
Labels: bug, javascript

**Comment by Jobin-S** [comment] 2020-07-30 08:39
great @saurabhdaware
